#!/usr/bin/perl
print <<END_OF_TEXT;

<P><FONT SIZE="+2">This is what Laos looks like:</FONT></P>
<P ALIGN="center"><IMG BORDER="0"
SRC="$ktini{townshipgraphics}/Laos.gif"></P>
<P ALIGN="left"><FONT SIZE="+2">Did you know?</FONT></P>
<UL>
<LI>
<P ALIGN="left"><FONT SIZE="+1">Laos is in Asia.
The capital of Laos is Vientiane.
Other cities include Sam Neua, Thakhek, and Vang Vieng.</FONT></P>
</LI>
<LI>
<P ALIGN="left"><FONT SIZE="+1">Laos is completely surrounded by other
countries; it has no connection to the sea.
However, its most valuable export is electricity generated by
hydroelectric power stations on the River Mekong.</FONT></P>
</LI>
<LI>
<P ALIGN="left"><FONT SIZE="+1">Once part of Indochina
(a group of Southeast Asia countries run by France),
Laos has been independent since 1950.</FONT></P>
</LI>
<LI>
<P ALIGN="left"><FONT SIZE="+1">Laos has no railroads and only very basic
roads.</FONT></P>
</LI>
</UL>
<BR><BR>
<H3><A HREF="$ktini{engine}?KEY=3054">Go back to the game!</A></H3>

END_OF_TEXT

